name: kart_project
description: A flutter-pi-app running on a RaspberryPi 4, being the infotainment system for a custom builded e-kart, planned by two brothers.

version: 0.1.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  provider: ^4.3.2+3
  intl: ^0.16.1

  # Design
  eva_icons_flutter: ^2.0.1
  overlay_support: ^1.0.5

  # Platform specific
  ffi: ^0.1.3
  flutter_gpiod: ^0.2.0
  wiring_pi_i2c:
    path: ../wiring_pi_i2c
  wiring_pi_serial:
    path: ../wiring_pi_serial
  ads1x15_rpi:
    path: ../ads1x15_rpi

  # Database
  sqflite_common_ffi: ^1.1.1+1
  shared_preferences: ^0.5.12+4

  # Map
  map: ^0.2.0+1
  latlng: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700

  assets:
    - assets/