name: kart_project
description: A flutter-pi-app running on a RaspberryPi 4, being the infotainment system for a custom builded e-kart, planned by two brothers.

version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  provider: ^5.0.0
  intl: ^0.17.0

  # Design
  eva_icons_flutter: ^3.0.0
  overlay_support: ^1.2.0

  # Platform specific
  ffi: ^1.0.0
  flutter_gpiod: ^0.4.0-nullsafety
  wiring_pi_soft_pwm:
    path: ../wiring_pi_soft_pwm
  wiring_pi_i2c:
    path: ../wiring_pi_i2c
  linux_can:
    path: ../linux_can/

  # Database
  sqflite_common_ffi: ^2.0.0
  shared_preferences: ^2.0.5

  # Map
  map: ^0.3.0
  latlng: ^0.1.0

flutter:
  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700

  assets:
    - assets/
