name: kart_project
description: A flutter-pi-app running on a RaspberryPi 4, being the infotainment system for a custom builded e-kart, planned by two brothers.

version: 0.1.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  provider: ^4.3.2+3
  intl: ^0.16.1

  # Design
  eva_icons_flutter: ^2.0.1
  overlay_support: ^1.0.5

  # Platform specific
  ffi: ^0.1.3
  flutter_gpiod: ^0.1.0+3

  # Database
  sqflite_common_ffi: ^1.1.0+1
  shared_preferences: ^0.5.8

  # Map
  latlong: ^0.6.1
  flutter_map: ^0.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700

  assets:
    - assets/